import {Store} from './store';

export const Notebooksbilliger: Store = {
  currency: '€',
  labels: {
    inStock: {
      container: '.product-detail__availability',
      text: [
        'sofort ab lager',
        'ca. 2-4 werktage',
        'ca. 5-10 werktage',
      ],
    },
    maxPrice: {
      container: '.product-price__price',
      euroFormat: true,
    },
    outOfStock: {
      container: '.product-detail__sold-out',
      text: ['dieses produkt ist leider ausverkauft.'],
    },
  },
  links: [
    {
      brand: 'test:brand',
      model: 'test:model',
      series: 'test:series',
      url: 'https://www.notebooksbilliger.de/gigabyte+geforce+rtx+3060+gaming+oc+12gb+grafikkarte+720833'
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/asus+rog+strix+geforce+rtx+3060+oc+12g+grafikkarte+702541',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/gigabyte+geforce+rtx+3060+gaming+oc+12gb+gddr6+grafikkarte+700421',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/gigabyte+geforce+rtx+3060+eagle+oc+12gb+gddr6+grafikkarte+700422',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/inno3d+geforce+rtx+3060+12gb+twin+x2+oc+701384',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/inno3d+geforce+rtx+3060+12gb+ichill+x3+red+701383?',
    },
    {
      brand: 'palit',
      model: 'dual',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/palit+geforce+rtx+3060+12gb+dual+702252',
    },
    {
      brand: 'palit',
      model: 'dual oc',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/palit+geforce+rtx+3060+12gb+dual+oc+gddr6+702251',
    },
    {
      brand: 'pny',
      model: 'xlr8 gaming',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/pny+geforce+rtx+3060+12gb+xlr8+gaming+revel+epic+x+rgb+single+701885',
    },
    {
      brand: 'zotac',
      model: 'amp white',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/zotac+geforce+rtx+3060+amp+white+12gb+gddr6+grafikkarte+701867',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3060',
      url: 'https://www.notebooksbilliger.de/zotac+gaming+geforce+rtx+3060+twin+edge+oc+12gb+grafikkarte+700378',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/inno3d+geforce+rtx+3070+ichill+x3+grafikkarte+684162',
    },
    {
      brand: 'inno3d',
      model: 'twin x2',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/inno3d+geforce+rtx+3070+twin+x2+grafikkarte+685496',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/inno3d+geforce+rtx+3070+twin+x2+oc+grafikkarte+685500',
    },
    {
      brand: 'gainward',
      model: 'phoenix',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/gainward+geforce+rtx+3070+phoenix+8gb+gddr6+grafikkarte+685073',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/gainward+geforce+rtx+3070+phoenix+gs+8gb+gddr6+grafikkarte+681575',
    },
    {
      brand: 'pny',
      model: 'uprising',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/pny+geforce+rtx+3070+8gb+uprising+dual+fan+edition+grafikkarte+685520',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/pny+geforce+rtx+3070+8gb+xlr8+gaming+revel+epic+x+rgb+685560',
    },
    {
      brand: 'asus',
      model: 'tuf',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/asus+tuf+gaming+geforce+rtx+3070+8gb+grafikkarte+685524',
    },
    {
      brand: 'zotac',
      model: 'twin edge',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/zotac+gaming+geforce+rtx+3070+twin+edge+8gb+gddr6+grafikkarte+677561',
    },
    {
      brand: 'zotac',
      model: 'twin edge oc',
      series: '3070',
      url: 'https://www.notebooksbilliger.de/zotac+gaming+geforce+rtx+3070+twin+edge+oc+8gb+gddr6+grafikkarte+684216',
    },
    {
      brand: 'gainward',
      model: 'phoenix gs',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/gainward+geforce+rtx+3080+phoenix+gs+10gb+gddr6x+grafikkarte+677618',
    },
    {
      brand: 'gigabyte',
      model: 'eagle oc',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/gigabyte+geforce+rtx+3080+eagle+oc+10gb+gddr6x+grafikkarte+677501',
    },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/gigabyte+geforce+rtx+3080+gaming+oc+10gb+gddr6x+grafikkarte+677499',
    },
    {
      brand: 'inno3d',
      model: 'ichill x3',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/inno3d+geforce+rtx+3080+ichill+x3+grafikkarte+678588',
    },
    {
      brand: 'inno3d',
      model: 'twin x2 oc',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/inno3d+geforce+rtx+3080+twin+x2+oc+grafikkarte+679190',
    },
    {
      brand: 'msi',
      model: 'gaming x trio',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/msi+geforce+rtx+3080+gaming+x+trio+10g+grafikkarte+678527',
    },
    {
      brand: 'palit',
      model: 'gaming pro',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/palit+geforce+rtx+3080+gamingpro+10gb+gddr6x+grafikkarte+677609',
    },
    {
      brand: 'palit',
      model: 'gaming pro oc',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/palit+geforce+rtx+3080+gamingpro+oc+10gb+gddr6x+grafikkarte+677606',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/pny+geforce+rtx+3080+xlr8+gaming+10gb+gddr6x+grafikkarte+677407',
    },
    {
      brand: 'pny',
      model: 'xlr8 revel',
      series: '3080',
      url: 'https://www.notebooksbilliger.de/pny+geforce+rtx+3080+10gb+xlr8+gaming+revel+epic+x+grafikkarte+677412',
    },
    {
      brand: 'asus',
      model: 'strix',
      series: '3090',
      url: 'https://www.notebooksbilliger.de/asus+rog+strix+geforce+rtx+3090+24gb+gddr6x+grafikkarte+677343',
    },
    {
      brand: 'asus',
      model: 'strix oc',
      series: '3090',
      url: 'https://www.notebooksbilliger.de/asus+rog+strix+geforce+rtx+3090+oc+24gb+gddr6x+grafikkarte+677308',
    },
    {
      brand: 'gigabyte',
      model: 'aorus master',
      series: '3090',
      url: 'https://www.notebooksbilliger.de/gigabyte+geforce+rtx+3090+master+24gb+gddr6x+grafikkarte+683868',
    },
    {
      brand: 'palit',
      model: 'gaming pro oc',
      series: '3090',
      url: 'https://www.notebooksbilliger.de/palit+geforce+rtx+3090+gamingpro+oc+24gb+gddr6x+grafikkarte+677599',
    },
    {
      brand: 'zotac',
      model: 'trinity',
      series: '3090',
      url: 'https://www.notebooksbilliger.de/zotac+gaming+geforce+rtx+3090+trinity+24gb+gddr6x+grafikkarte+677550',
    },
    {
      brand: 'amd',
      model: '5600x',
      series: 'ryzen5600',
      url: 'https://www.notebooksbilliger.de/amd+ryzen+5+5600x+cpu+684022',
    },
    {
      brand: 'amd',
      model: '5800x',
      series: 'ryzen5800',
      url: 'https://www.notebooksbilliger.de/amd+ryzen+ryzen+7+5800x+cpu+684018',
    },
    {
      brand: 'amd',
      model: '5900x',
      series: 'ryzen5900',
      url: 'https://www.notebooksbilliger.de/amd+ryzen+9+5900x+cpu+684032',
    },
    {
      brand: 'amd',
      model: '5950x',
      series: 'ryzen5950',
      url: 'https://www.notebooksbilliger.de/amd+ryzen+9+5950x+cpu+684033',
    },
    // {
    //   brand: 'asus',
    //   model: 'astral',
    //   series: '5080',
    //   url: '',
    // },
    {
      brand: 'asus',
      model: 'astral oc',
      series: '5080',
      url: 'https://www.notebooksbilliger.de//asus+rog+astral+geforce+rtx+5080+876601',
    },
    // {
    //   brand: 'asus',
    //   model: 'prime',
    //   series: '5080',
    //   url: '',
    // },
    {
      brand: 'asus',
      model: 'prime oc',
      series: '5080',
      url: 'https://www.notebooksbilliger.de/asus+prime+geforce+rtx+5080+oc+876479',
    },
    // {
    //   brand: 'asus',
    //   model: 'tuf',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'asus',
    //   model: 'tuf oc',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'gainward',
    //   model: 'phantom',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'gainward',
    //   model: 'phantom gs',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'gainward',
    //   model: 'phoenix',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'gigabyte',
    //   model: 'aorus master',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'gigabyte',
    //   model: 'aorus master ice',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'gigabyte',
    //   model: 'aorus xtreme waterforce',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'gigabyte',
    //   model: 'aorus xtreme waterforce wb',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'gigabyte',
    //   model: 'aero oc sff',
    //   series: '5080',
    //   url: '',
    // },
    {
      brand: 'gigabyte',
      model: 'gaming oc',
      series: '5080',
      url: 'https://www.notebooksbilliger.de/gigabyte+geforce+rtx+5080+gaming+oc+16g+876606',
    },
    {
      brand: 'gigabyte',
      model: 'windforce oc sff',
      series: '5080',
      url: 'https://www.notebooksbilliger.de/gigabyte+geforce+rtx+5080+windforce+oc+sff+16g+876603',
    },
    // {
    //   brand: 'inno3d',
    //   model: 'x3',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'inno3d',
    //   model: 'x3 oc',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'msi',
    //   model: 'gaming trio oc',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'msi',
    //   model: 'gaming trio oc white',
    //   series: '5080',
    //   url: '',
    // },
    {
      brand: 'msi',
      model: 'suprim soc',
      series: '5080',
      url: 'https://www.notebooksbilliger.de/msi+geforce+rtx+5080+16g+suprim+soc+876473',
    },
    // {
    //   brand: 'msi',
    //   model: 'suprim liquid soc',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'msi',
    //   model: 'vanguard soc launch edition',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'msi',
    //   model: 'ventus 3x',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'msi',
    //   model: 'ventus 3x oc',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'msi',
    //   model: 'ventus 3x oc white',
    //   series: '5080',
    //   url: '',
    // },
    {
      brand: 'zotac',
      model: 'amp extreme infinity',
      series: '5080',
      url: 'https://www.notebooksbilliger.de//zotac+gaming+geforce+rtx+5080+amp+extreme+infinity+876830',
    },
    // {
    //   brand: 'zotac',
    //   model: 'solid',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'zotac',
    //   model: 'solid oc',
    //   series: '5080',
    //   url: '',
    // },
    // {
    //   brand: 'asus',
    //   model: 'astral',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'asus',
    //   model: 'astral oc',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'asus',
    //   model: 'astral lc',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'asus',
    //   model: 'astral lc oc',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'asus',
    //   model: 'tuf',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'asus',
    //   model: 'tuf oc',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'gainward',
    //   model: 'phantom',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'gigabyte',
    //   model: 'aorus master ice',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'inno3d',
    //   model: 'x3',
    //   series: '5090',
    //   url: '',
    // },
    {
      brand: 'msi',
      model: 'gaming trio oc',
      series: '5090',
      url: 'https://www.notebooksbilliger.de/msi+geforce+rtx+5090+32g+gaming+trio+oc+876678',
    },
    // {
    //   brand: 'msi',
    //   model: 'suprim soc',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'msi',
    //   model: 'suprim liquid soc',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'msi',
    //   model: 'vanguard soc launch edition',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'msi',
    //   model: 'ventus 3x oc',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'zotac',
    //   model: 'amp extreme infinity',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'zotac',
    //   model: 'solid',
    //   series: '5090',
    //   url: '',
    // },
    // {
    //   brand: 'zotac',
    //   model: 'solid oc',
    //   series: '5090',
    //   url: '',
    // }
  ],
  name: 'notebooksbilliger',
};
